//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonToCsharpPoco.Ui.Ui.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonToCsharpPoco.Resources.Localizer", typeof(Localizer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Json Attribute.
        /// </summary>
        internal static string AddJsonAttribute_Label {
            get {
                return ResourceManager.GetString("AddJsonAttribute_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array Type.
        /// </summary>
        internal static string ArrayType_Label {
            get {
                return ResourceManager.GetString("ArrayType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# code copied to clipboard.
        /// </summary>
        internal static string ClipboardCopySuccess {
            get {
                return ResourceManager.GetString("ClipboardCopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Failed.
        /// </summary>
        internal static string ConversionFailed {
            get {
                return ResourceManager.GetString("ConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Successful.
        /// </summary>
        internal static string ConversionSuccess {
            get {
                return ResourceManager.GetString("ConversionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string Convert_Button {
            get {
                return ResourceManager.GetString("Convert_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting....
        /// </summary>
        internal static string Converting_Label {
            get {
                return ResourceManager.GetString("Converting_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Code.
        /// </summary>
        internal static string CopyCode_Button {
            get {
                return ResourceManager.GetString("CopyCode_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Editor.
        /// </summary>
        internal static string CsharpEditor_Label {
            get {
                return ResourceManager.GetString("CsharpEditor_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized Default Values.
        /// </summary>
        internal static string DefaultValues_Label {
            get {
                return ResourceManager.GetString("DefaultValues_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter JSON to convert.
        /// </summary>
        internal static string EnterJson {
            get {
                return ResourceManager.GetString("EnterJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file:.
        /// </summary>
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload Error.
        /// </summary>
        internal static string FileUploadError {
            get {
                return ResourceManager.GetString("FileUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable?.
        /// </summary>
        internal static string IsNullable_Label {
            get {
                return ResourceManager.GetString("IsNullable_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string IsRequired_Label {
            get {
                return ResourceManager.GetString("IsRequired_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting JSON to C# POCO.
        /// </summary>
        internal static string JsonConversionError {
            get {
                return ResourceManager.GetString("JsonConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON converted to C# POCO.
        /// </summary>
        internal static string JsonConversionSuccess {
            get {
                return ResourceManager.GetString("JsonConversionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Editor.
        /// </summary>
        internal static string JsonEditor_Label {
            get {
                return ResourceManager.GetString("JsonEditor_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        internal static string Namespace_Label {
            get {
                return ResourceManager.GetString("Namespace_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming Settings.
        /// </summary>
        internal static string NamingSettings_Title {
            get {
                return ResourceManager.GetString("NamingSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Access.
        /// </summary>
        internal static string PropertyAccess_Label {
            get {
                return ResourceManager.GetString("PropertyAccess_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Settings.
        /// </summary>
        internal static string PropertySettings_Title {
            get {
                return ResourceManager.GetString("PropertySettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Name.
        /// </summary>
        internal static string RootName_Label {
            get {
                return ResourceManager.GetString("RootName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the content of your editor for future sessions?.
        /// </summary>
        internal static string SaveEditor_Description {
            get {
                return ResourceManager.GetString("SaveEditor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Your data will be stored locally and should not include confidential information. You can disable this feature if needed..
        /// </summary>
        internal static string SaveEditor_Note {
            get {
                return ResourceManager.GetString("SaveEditor_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Editor Content.
        /// </summary>
        internal static string SaveEditor_Title {
            get {
                return ResourceManager.GetString("SaveEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember your settings for next time.
        /// </summary>
        internal static string SaveSettings_Description {
            get {
                return ResourceManager.GetString("SaveSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string SaveSettings_Title {
            get {
                return ResourceManager.GetString("SaveSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your preferred language.
        /// </summary>
        internal static string Select_Preferred_Language {
            get {
                return ResourceManager.GetString("Select_Preferred_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred appearance.
        /// </summary>
        internal static string Theme_Description {
            get {
                return ResourceManager.GetString("Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme_Title {
            get {
                return ResourceManager.GetString("Theme_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Settings.
        /// </summary>
        internal static string TypeSettings_Title {
            get {
                return ResourceManager.GetString("TypeSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        internal static string UploadFile_Label {
            get {
                return ResourceManager.GetString("UploadFile_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace file scoped.
        /// </summary>
        internal static string UseFileScoped_Label {
            get {
                return ResourceManager.GetString("UseFileScoped_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Primary Constructor.
        /// </summary>
        internal static string UsePrimaryConstructor_Label {
            get {
                return ResourceManager.GetString("UsePrimaryConstructor_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Records.
        /// </summary>
        internal static string UseRecords_Label {
            get {
                return ResourceManager.GetString("UseRecords_Label", resourceCulture);
            }
        }
    }
}
